### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Stevo6** [int19h/aow-patch#2]
I tried running the patch and it seems to hang on creating backup copy, and throws an error backing up, access is denied to Ilpack.dpl.bak
I changed the permissions for AOW file to everyone and ran the patch as admin

**Comment by int19h** [comment]
Yep, it does expect to be able to write to the installation folder. Steam and GOG installs are both writeable, so it should work in the most common case. Did you install the game directly from CD, by chance?

**Comment by MBBENSON** [comment]
I'm having a similar issue - I have a Steam installation on the same drive as Steam, but not the same as my OS. My patcher fails at the "installing patch" phase with the error message "Failed to Apply Patch: Access is Denied." I have marked the entire installation folder as accessible to all users and unchecked "read only" in properties, and I still get the error when running the patcher as an Administrator.

**Comment by int19h** [comment]
This sounds like it might be antivirus or some other kind of anti-malware preventing modification of executable files - many of those treat anything that tries to patch a binary as potential malware and proactively block it. If you're using Windows built-in protection, check the log in Settings -> Windows Security -> Protection History.

Last time someone ran into a similar issue, it was when I released v2 of the patch - that changed the way in which the binary is patched to work for all the different language versions of AoW, but it also made it more likely to trip the malware heuristic. So unless you specifically need to patch a non-English version, try https://github.com/int19h/aow-patch/releases/tag/v1 and see if that helps.

**Comment by MBBENSON** [comment]
The issue is resolved for me - my procedure this time was:

1. I did a clean install of Age of Wonders from Steam
2. (New) I followed the procedure in [this GoG forum thread](https://www.gog.com/forum/age_of_wonders_series/aow_1_crashes_on_startup_win7x64_desktop/post1) to manually add all the Age of Wonders executables to the Data Execution Prevention Exceptions List in my computer settings.
3. I installed the patcher in administrator mode and it worked just fine, even without manually unchecking "read-only" on all the executables.
4. I set all the Age of Wonders Executables to use Compatibility Mode for Windows XP (Service Pack 2)
5. At this point, the game worked for me, but the editor kept crashing whenever I opened or started a new map.
6. I changed the Compatibility Mode for AoWEd.exe to Windows 8
7. At this point, all vanilla game functions work for me and the only crash I had happened when I let the display turn off while playing in full-screen, which the game really did not like. :P

I'm going to try out the unofficial patch today and see how it goes. Should I re-install your patch after any other patches I make to keep your changes on top of the load order, so to speak?

*Edit* The Steam version is already patched to 1.36, so no patching needed. :)

**Comment by int19h** [comment]
Yeah, Steam and GoG both provide fully patched AoW; the only time you should need to manually install a patch is if you somehow had a CD installer around. For what it's worth, the patch will likely work with older versions of the game, but I've only ever tested it with 1.36. 

Running it maximized windowed seems to be the best for stability in general, although you do lose mouse edge scrolling that way.
